input = "../input"
initial_seed = 5892132
ncpus = 16

total_simulations = 100
interface = [5, 6]

starting_conf_pattern = "../SHOOT_2/success_*.dat"

[log]
filename = "ffs.log"
also_stderr = true
#verbose = true
