input = "../input"
initial_seed = 5892132
ncpus = 16

total_simulations = 10000
interface = [4, 5]

starting_conf_pattern = "../SHOOT_1/success_*.dat"

[log]
filename = "ffs.log"
also_stderr = true
#verbose = true
